### ISSUE TITLE
move contract state off-ledger to IPFS

### ISSUE THREAD

**Issue by brenzi** [hyperledger-labs/private-data-objects#102]
Currently, PDO stores the contract state on the ledger. For the sake of avoiding ledger-bloat, I suggest to commit ledger state updates to [IPFS](https://ipfs.io/) and only commiting the IPFS hash to the ledger. Enclave services can then retrieve the latest state hash from the ledger and lookup the actual state on IPFS.

What are the dev's thoughts on this?

**Comment by cmickeyb** [comment]
Not sure if you've looked at the new persistent key-value store, but it enables off-chain state storage. Currently, we plan to implement a "proof of replication" in the eservices that are provisioned for the contract. However, it would be relatively straight forward to store the state blocks in IPFS. Take a look at python/pdo/contract/state.py for the code that caches the state blocks.

**Comment by cmickeyb** [comment]
I'm going to close this. Recent PRs implement an "off-chain" storage service. We will be adding replication (and a proof of replication requirement in the TP) to ensure block availability.
