### ISSUE TITLE
integer-key contract unittest fails

### ISSUE THREAD

**Issue by brenzi** [hyperledger-labs/private-data-objects#103]
I've tried to run integer-key unit tests like this

```
cd contracts
make debug
cd integer-key
export LD_LIBRARY_PATH=<PDO path>/common/build
tinyscheme _debug_integer-key.scm 
```
resulting in
```
ERROR: (_debug_integer-key.scm : 241) open-input-string: argument 1 must be: string; 
```

funny enough, that file has 240 lines. 

similar error for auction contract:
```
Auction is primed
Initial bids submitted
Error: (_debug_auction.scm : 260) open-input-string: argument 1 must be: string 
Errors encountered reading _debug_auction.scm
```
line 260 reads:
```
(display "Bids updated\n")
```

Is this the official way to run unit tests at all? Is there any doc on how to unit test contracts?

**Comment by cmickeyb** [comment]
the test should be fixed in the PR for the new contracts. the debugging tests in the contracts directory are not currently executed in the run-tests script. I need to fix that.

**Comment by cmickeyb** [comment]
and... i'm not sure why tinyscheme does it, but the lines are 0 based. So look at line 259 for the actual error.

**Comment by cmickeyb** [comment]
This should be resolved.
