### ISSUE TITLE
Update documentation to cover SGX HW configuration steps

### ISSUE THREAD

**Issue by cmickeyb** [hyperledger-labs/private-data-objects#105]
There are bits and pieces in the documentation that covers the steps necessary to get HW support for the contract enclave. However, we don't have the same level of "cookbook" documentation that we attempt to provide for the rest of the packages. Need to include a "how to configure" document that is linked from the top level document (what you would do before you run build).

**Comment by g2flyer** [comment]
To get get SGX HW mode work in docker/docker-compose i'm currently revamping some of the build process as well as the way the MRENCLAVE and BASENAME are extracted/configured (simplify to get them without having to have related code in enclave and having to run enclave) which might slightly change the steps but i had it also on the list to update doc (e.g., referencing eservice/register_with_ledger.sh in sawtooth/docs/SETUP.md and obviously documenting my changes).   

The docker compose files might hopefully make it easier to run with SGX (although initial sawtooth integration would be only via default consensus, not HW-mode PoET ...)

**Comment by cmickeyb** [comment]
@g2flyer i have updates to the script the @bvavala wrote to make it more robust. specifically, its necessary to shutdown the enclave module or all the threads will hang around forever.

also... writing up a suggestion for simplifying configuration that should help.

**Comment by bvavala** [comment]
addressed in #207
