### ISSUE TITLE
Exchange documentation  typeo

### ISSUE THREAD

**Issue by cheevo** [hyperledger-labs/private-data-objects#113]
https://github.com/hyperledger-labs/private-data-objects/blob/master/contracts/exchange/docs/exchange.md 
Red Marbles Player Association (RMPA) -- an oversight organization that tracks blue marble banks
should read
Red Marbles Player Association (RMPA) -- an oversight organization that tracks red marble banks

**Comment by cmickeyb** [comment]
@cheevo feel free to submit a PR for the change!
