### ISSUE TITLE
Enclave Service Documentation conflicting descriptions

### ISSUE THREAD

**Issue by cheevo** [hyperledger-labs/private-data-objects#114]
The powerpoint  https://docs.google.com/presentation/d/16V0kK9M_z86WwI-PfdltY5plXnkOdFuK84sWFaExH_k/edit#slide=id.p14 says
"Enclave service takes care of registering/revoking/updating enclaves"

The 
https://github.com/hyperledger-labs/private-data-objects/blob/master/eservice/docs/eservice.md
says
"The contract enclave service is an HTTP server that passes messages between a client and a contract enclave."
Confusing ?

**Comment by cmickeyb** [comment]
Agreed. The enclave service, on first run loads the enclave, initializes it and then registers it. After the first run, however, its primary functionality is to pass messages between the client & the enclave. So... both are correct but neither is complete.

**Comment by bvavala** [comment]
Solved in 9df5fc7 and in the presentation -- thank you, cheevo!
