### ISSUE TITLE
Documentation  improvement  PdoProvisioningKeyToStateSecretMap in cregistry.md

### ISSUE THREAD

**Issue by cheevo** [hyperledger-labs/private-data-objects#128]
Documentation improvement in
(https://github.com/hyperledger-labs/private-data-objects/blob/master/sawtooth/docs/cregistry.md)

Add a Link to  PdoProvisioningKeyToStateSecretMap
(https://github.com/hyperledger-labs/private-data-objects/blob/master/python/sawtooth/pdo_protos/protobufs/pdo_contract_registry.proto)
or 
Actually add copy of what is in the .proto file
```
message PdoProvisioningKeyToStateSecretMap {
    // Public key generated by the provisioning services
    string provisioning_service_public_key = 1;

    // An encrypted contract secret generated by the provisioning service
    string provisioning_contract_state_secret = 2;

    // Index defining the enclave info ordering for signing
    int32 index = 3;
}
```
Ideally the wiki  for each Transaction family .md file  would have url to the relevant .proto file in the git

**Comment by cmickeyb** [comment]
no more sawtooth.
