### ISSUE TITLE
PDO  tp context.get_state error

### ISSUE THREAD

**Issue by lakshaygaur** [hyperledger-labs/private-data-objects#22]
Hi ,

I get this following error/warning with PDO transaction processor when running enclave register with simulated proof data.

`unexpected exception occurred on context.get_state([0b936fca070f54db6c0a03e3df66dbae0428e27f1bd93a08c8708b455be5ab70fbfd66])`

**Comment by byron-marohn** [comment]
Hi @lakshaygaur 

Thanks for the report. Can you add some more information? 

- What program output that error message - the PDO transaction processor? Or one of the enclave service scripts used to do the registration? 
- Is there any other debugging output available? Most errors like this generate a stacktrace (though not all of them). If you got more error text, please include it also. 

Depending on what program you're running, you may be able to provide a `-loglevel DEBUG -logfile __screen__` arguments to get even more debugging information which would help me identify the problem.

**Comment by lakshaygaur** [comment]
Hi @byron-marohn 

PDO transaction processor output this error message. I used this command to register enclave service.
`../bin/pdo-cli json --keyfile key-enclave.priv --wait 10 enclave-register-without-proof-data.json`

The logs that I got from PDO terminal are below : 
![image](https://user-images.githubusercontent.com/26569986/41035355-01635e1c-69aa-11e8-8938-94a9acdf651e.png)

Thanks

**Comment by EugeneYYY** [comment]
Hi @lakshaygaur

Normally, an enclave cannot be submitted without proof-data (a.k.a. empty proof data) hence a log message stating "unexpected exception" (wording can/should be improved). It is also followed by a line indicating that it can be an enclave running in SGX simulation mode "*** Enclave proof data is empty ...".  
If PDO TP runs in a debug (it seems to be your case) with command line option --debug-on, this enclave will be successfully registered and the messages above are purely informative.
If PDO TP runs in none debug mode, the enclave registration will be rejected and these messages can help to debug the issue. 
Let me know if this answers your question.

**Comment by lakshaygaur** [comment]
@EugeneYYY So Im getting this informative debug messages i.e `unexpected exception occurred on context.get_state` cause of debug mode on and cause Im running it in simulation mode ?
So if this wasnt simulation mode PDO TP would be getting context .getstate data ?

**Comment by EugeneYYY** [comment]
That is correct. As matter of fact folder sawtooth/tests includes two enclave registration payload files enclave-register-with-simulated-proof-data.json and enclave-register-without-proof-data.json correspondingly with and without proof data. The former file won't cause this message. A side note: word "simulated" in the name of the former file means that the proof data are generated not for real SGX HW enclave, but were pre-generated for sign of life test only.

**Comment by lakshaygaur** [comment]
@EugeneYYY  Ive tried running PDO TP in simulation mode with-proof-data as well but i was getting this same exception.

**Comment by EugeneYYY** [comment]
@lakshaygaur 
I just realized that I have partially incorrectly answered your question. My prior answer is correct re: "*** Enclave proof data is empty - simulation mode", but not re: "Unexpected exception occurred on context.get_state(...)" The latter currently should happen on any enclave registration.
TP first checks if an enclave with the same id (a.k.a. verification key) is already exists and, if TP doesn't find a global Sawtooth state for the enclave id, it will proceed with the new enclave registration. So this is an informative log entry. Currently enclave registry supports only new enclave registration and this log message may seems unneeded. In the future additional actions - enclave registration update and enclave cancel - will be supported and this error will be meaningful fir debugging them. The error is reported by a lower code level that is not aware of the action type being processed. That is why it is reported now even though it is better to not report it or report an another log meesage. 
Now I understand that it can be confusing and I'll look into disabling this log message in case of enclave registration. Thank you for pointing it out.
For now treat it as a purely informative message that can be ignored.
