### ISSUE TITLE
Set commit worker threads as daemons

### ISSUE THREAD

**Issue by prakashngit** [hyperledger-labs/private-data-objects#222]
Currently, CTRL-C does not exit the commit threads (unless with explicit termination signals). Explicitly set the commit threads as daemons to exit these as well when the main thread terminates.

**Comment by cmickeyb** [comment]
The threads don't necessarily need to be made daemons.

You can just register an "atexit" function that shuts down the threads.

At this point, I think we need an "initialize_pdo" function in the client that we always call to init the modules. That function could start the replication threads and then register the atexit() function to shutdown the threads cleanly.

**Comment by prakashngit** [comment]
agreed, i dint know about atexit() until now. A cleaner solution than converting threads to daemons (i prefer non-daemon threads to enable completion of background tasks & a clean exit function rather than abruptly killing threads, especially when there is no error, and the main threads just wants to exit)

**Comment by cmickeyb** [comment]
Done.
