### ISSUE TITLE
Produce a single contract interpreter library per interpreter type

### ISSUE THREAD

**Issue by masomel** [hyperledger-labs/private-data-objects#247]
Now that, the interpreter is abstracted away, it would be nice to provide developers with a single interpreter-specific library such as `libpdo_wawaka.a`. This would allow a developer to see whether they are importing the PDO interpreter for wawaka or gipsy. We would then ideally hide the interpreter-specific dependencies (e.g. libtinyscheme.a vs libiwasm.a).

See discussion: https://github.com/hyperledger-labs/private-data-objects/pull/245#discussion_r375593292

**Comment by cmickeyb** [comment]
Done
