### ISSUE TITLE
Avoid getting root block from Sawtooth ledger, instead get it from Storage service

### ISSUE THREAD

**Issue by prakashngit** [hyperledger-labs/private-data-objects#263]
Sawtooth ledger originally stored the contract state root block as part of ccl updates transactions. The `get_from_ledger` method appearing in state.py was used to retrieve this block from Sawtooth. 

Given that all blocks now are available at externalized storage services, use the `get_from_storage_service` API instead of `get_from_ledger` wherever the root block is necessary. 

(A bit of code refactoring is necessary to use the new API, so flagging this as an issue for now).

The above API gets used only when PDO is deployed with multiple clients residing on multiple nodes  ( so that state cache is not shared)

Currently, the SW raises an exception if get_from_ledger is called. Note that the CCF based ledger does not store the root block in the ledger at all.

**Comment by marcelamelara** [comment]
Support for Sawtooth was removed in #417.
