### ISSUE TITLE
Remove libupdo-crypto dependency on SGX SDK

### ISSUE THREAD

**Issue by masomel** [hyperledger-labs/private-data-objects#268]
Currently, `libupdo-crypto` requires `sgx_error.h` from the SGX SDK even though, no untrusted PDO code uses any SGX APIs. Removing the dependency on the SGX SDK would also enable the standalone use of `libpdo-crypto` in other environments that don't provide the SGX SDK (e.g. Graphene).

See https://github.com/hyperledger-labs/private-data-objects/pull/267#discussion_r413263196 for some more discussion.

**Comment by cmickeyb** [comment]
Done.
