### ISSUE TITLE
Add high-level documentation on compile-time memory options for wawaka

### ISSUE THREAD

**Issue by masomel** [hyperledger-labs/private-data-objects#277]
Emscripten allows developers to configure certain WASM module-specific memory parameters that need to fit within the pre-reserved wawaka-wide memory pool. We currently use the same emscripten settings for all test contracts, but we should document at a high level how some of these settings relate to the wawaka-wide memory configuration.

**Comment by marcelamelara** [comment]
Emscripten no longer supported. This was added for WAMR in #275
