### ISSUE TITLE
assert `verify_store_signature` does not raise exception in case of internal crypto error

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/private-data-objects#288]
The `assert` command [here](https://github.com/hyperledger-labs/private-data-objects/blob/ed199f38efbff6d50e3db13ad4adf6c1846f2e29/python/pdo/test/storage.py#L111) checks the `verify_store_signature` return value as a boolean value.
However, such return value originates from [the signature verification API](https://github.com/hyperledger-labs/private-data-objects/blob/fce68acd5e51043b54ce2fdf7509e568f5402552/common/crypto/sig_public_key.h#L61) in the crypto lib, and it is a `int` -- the SWIG conversion should maintain the type. Most importantly, this value is `-1` when there is an internal error in the crypto lib. In this case, the `assert` above does not raise any exception.
Also, this happens in other places.

Proposed solution: change the assert argument to (`result > 0`).

**Comment by cmickeyb** [comment]
result >= 0?

**Comment by bvavala** [comment]
No, I think it should be `result > 0`, because 0 means invalid and -1 means error

**Comment by bvavala** [comment]
Addressed in #486
