### ISSUE TITLE
Replace the use of "HOSTNAME" in CCF config with processing the PDO_LEDGER_URL 

### ISSUE THREAD

**Issue by cmickeyb** [hyperledger-labs/private-data-objects#296]
The documentation for CCF suggests that the environment variable HOSTNAME should be changed. However, this variable is generally used as a builtin for bash. We already have the host name in the PDO_LEDGER_URL, suggest that we parse it out and use that to minimize the number of configuration variables that are necessary.

**Comment by marcelamelara** [comment]
@prakashngit @cmickeyb Has this been addressed yet?
