### ISSUE TITLE
sgx_spid.txt: No such file or Directory

### ISSUE THREAD

**Issue by zlonqi** [hyperledger-labs/private-data-objects#325]
I followed by that

> Access to IAS requires that a service provider create an identity (SPID) and a client authentication key. To create the SPID and the key you first need to register with the Intel Developer Portal.
> 
> Once your registration is complete subscribe for a linkable quote to create the client authentication key. The key will be available from your profile page.
> 
> Assuming that existing keys are found in ${PDO_SGX_KEY_ROOT} (which defaults to the directory ${PDO_SOURCE_ROOT}/build/keys/sgx_mode_${SGX_MODE,,}), copy the key from your profile page into a file called ${PDO_SGX_KEY_ROOT}/sgx_spid_api_key.txt.
> 
> In addition, your SPID can be found on your developer portal profile page. Copy the contents of the SPID into the file ${PDO_SGX_KEY_ROOT}/sgx_spid.txt.

and i run command  make SGX_MODE=HW -C docker test
but i get error message:

> cat: /project/pdo/build/opt/pdo/etc/keys/sgx//sgx_spid.txt: no such file or dir
> warning: PDO_SPID is not defined correctly, should be a a 32-byte hex key.
> make: *** verify-pre-conf Error 255
my machine is i5-7500(support SGX), ubuntu 20.04

can you help me, thank you very much.

**Comment by bvavala** [comment]
As you're running PDO in SGX HW mode, make sure that:
* you have properly set the `build/keys/sgx_mode_hw/sgx_spid.txt` and `build/keys/sgx_mode_hw/sgx_spid_api_key.txt` files with the values available in your account on [Intel's trusted services portal](https://api.portal.trustedservices.intel.com/);
* export all the necessary [environment variables](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/docs/environment.md), e.g., `export SGX_MODE=HW`;
* run `source build/common-config.sh`, this will set up additional environment variables
* double check the expected values with `echo "$PDO_SPID - $PDO_SPID_API_KEY"` (in HW mode, `DEADBEEF00000000DEADBEEF00000000 - deadbeef00000000deadbeef00000000` is _not_ the expected output; you should see your SPID and API key)
* finally, go ahead with `make -C docker test`

**Comment by zlonqi** [comment]
> As you're running PDO in SGX HW mode, make sure that:
> 
>     * you have properly set the `build/keys/sgx_mode_hw/sgx_spid.txt` and `build/keys/sgx_mode_hw/sgx_spid_api_key.txt` files with the values available in your account on [Intel's trusted services portal](https://api.portal.trustedservices.intel.com/);
> 
>     * export all the necessary [environment variables](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/docs/environment.md), e.g., `export SGX_MODE=HW`;
> 
>     * run `source build/common-config.sh`, this will set up additional environment variables
> 
>     * double check the expected values with `echo "$PDO_SPID - $PDO_SPID_API_KEY"` (in HW mode, `DEADBEEF00000000DEADBEEF00000000 - deadbeef00000000deadbeef00000000` is _not_ the expected output; you should see your SPID and API key)
> 
>     * finally, go ahead with `make -C docker test`

thank you very much! After  I set SGX_MODE=HW, I can successfully valid my SPID and API key got from Intel by execute build/common-config.sh. 
But I make it, it also warning: 

> cat: /project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/sgx_spid.txt: No such file or directory
> cat: /project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/sgx_spid_api_key.txt: No such file or directory
But I really don't locate the path it hints:   `/project/pdo/src/*`

**Comment by bvavala** [comment]
> I can successfully valid my SPID and API key got from Intel by execute build/common-config.sh

That is not meant to be executed, but rather "sourced" -- otherwise the variables will not be set properly.
Again: `source build/common-config.sh`

> But I really don't locate the path it hints: /project/pdo/src/*

That's a path in the docker container, not on your host platform.
Again, please make sure you have your SGX material (spid and api key) in `build/keys/sgx_mode_hw/`.
The PDO docker build will then map this material to the default `/project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/` location in the container.

**Comment by zlonqi** [comment]
> > I can successfully valid my SPID and API key got from Intel by execute build/common-config.sh
> 
> That is not meant to be executed, but rather "sourced" -- otherwise the variables will not be set properly.
> Again: `source build/common-config.sh`
> 
> > But I really don't locate the path it hints: /project/pdo/src/*
> 
> That's a path in the docker container, not on your host platform.
> Again, please make sure you have your SGX material (spid and api key) in `build/keys/sgx_mode_hw/`.
> The PDO docker build will then map this material to the default `/project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/` location in the container.

Thank you again. I chsh from zsh to bash, and I can source correctly. But when I make it, it fault at:

>  MAYBE: test , e.g., with 'ps', whether all services are up properly
>  # - insitialize the ledger
>  docker-compose   -f sawtooth-pdo.yaml  -f sawtooth-pdo.local-code.yaml  exec -T validator sawset proposal create --url http://rest-api:8008 --key /root/.sawtooth/keys/my_key.priv sawtooth.validator.transaction_families='[{"family": "intkey", "version": "1.0"}, {"family":"sawtooth_settings", "version":"1.0"}, {"family": "pdo_contract_enclave_registry", "version": "1.0"}, {"family":  "pdo_contract_instance_registry", "version": "1.0"}, {"family": "ccl_contract", "version": "1.0"}]'
>  Error: Unable to connect to "http://rest-api:8008": make sure URL is correct
>  make: *** [Makefile:96：test-env-setup-with-no-build] Error 1

**Comment by zlonqi** [comment]
> > I can successfully valid my SPID and API key got from Intel by execute build/common-config.sh
> 
> That is not meant to be executed, but rather "sourced" -- otherwise the variables will not be set properly.
> Again: `source build/common-config.sh`
> 
> > But I really don't locate the path it hints: /project/pdo/src/*
> 
> That's a path in the docker container, not on your host platform.
> Again, please make sure you have your SGX material (spid and api key) in `build/keys/sgx_mode_hw/`.
> The PDO docker build will then map this material to the default `/project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/` location in the container.

Thank you again. I chsh from zsh to bash, and I can source correctly. But when I make it, it fault at:

>  MAYBE: test , e.g., with 'ps', whether all services are up properly
>  # - insitialize the ledger
>  docker-compose   -f sawtooth-pdo.yaml  -f sawtooth-pdo.local-code.yaml  exec -T validator sawset proposal create --url http://rest-api:8008 --key /root/.sawtooth/keys/my_key.priv sawtooth.validator.transaction_families='[{"family": "intkey", "version": "1.0"}, {"family":"sawtooth_settings", "version":"1.0"}, {"family": "pdo_contract_enclave_registry", "version": "1.0"}, {"family":  "pdo_contract_instance_registry", "version": "1.0"}, {"family": "ccl_contract", "version": "1.0"}]'
>  Error: Unable to connect to "http://rest-api:8008": make sure URL is correct
>  make: *** [Makefile:96：test-env-setup-with-no-build] Error 1

**Comment by zlonqi** [comment]
> > I can successfully valid my SPID and API key got from Intel by execute build/common-config.sh
>
> That is not meant to be executed, but rather "sourced" -- otherwise the variables will not be set properly.
> Again: `source build/common-config.sh`
>
> > But I really don't locate the path it hints: /project/pdo/src/*
>
> That's a path in the docker container, not on your host platform.
> Again, please make sure you have your SGX material (spid and api key) in `build/keys/sgx_mode_hw/`.
> The PDO docker build will then map this material to the default `/project/pdo/src/private-data-objects/build/keys/sgx_mode_hw/` location in the container.

Thank you very much again!  After I run `source build/common-config.sh`, and I double check the expected values with echo "$PDO_SPID - $PDO_SPID_API_KEY", it print the  result I expected.
With I run `make -C docker test`, it also hault at below:

`
/project/pdo/src/private-data-objects/build/__tools__/verify-pre-conf.sh
tput: No value for $TERM and no -T specified
 verify-pre-conf.sh: --------------- CONFIG AND ENVIRONMENT PRE-CONF CHECK ---------------
 WARNING: PDO_SPID is not defined correctly, should be a a 32-byte hex key
make: *** [verify-pre-conf] Error 255
Makefile:118: recipe for target 'verify-pre-conf' failed
`
The good message it shows that SPID's path is correct.  Is the value falut? but I run `echo $PDO_SPID` that output:

> ABAC66755CB4E6424B04F96CC07C21C7
the value is I expected: a 32-byte hex key . I really don't know how to solve it now.

**Comment by bvavala** [comment]
> Thank you very much again! After I run source build/common-config.sh, and I double check the expected values with echo "$PDO_SPID - $PDO_SPID_API_KEY", it print the result I expected.

Good!

> The good message it shows that SPID's path is correct. Is the value falut? but I run echo $PDO_SPID that shows: ABAC66755CB4E6424B04F96CC07C21C7

That's what you want to see -- it appears to be a valid SPID.

> WARNING: PDO_SPID is not defined correctly, should be a a 32-byte hex key
make: *** [verify-pre-conf] Error 255
Makefile:118: recipe for target 'verify-pre-conf' failed

This is not right, you should double check you environment/configuration.
When you `source` the script file above, the script sets and "exports" several environment variables, including `$PDO_SPID`. However, in your case, `$PDO_SPID` doesn't appear to be set when `verify-pre-conf.sh` runs.
This likely means that you have `$PDO_SPID` set in your shell, but not exported to make it visible to other processes.
I would suggest you to retry in clean environment.

**Comment by bvavala** [comment]
Answering to https://github.com/hyperledger-labs/private-data-objects/pull/302#issuecomment-896128893

As explained [here](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/docker/Dockerfile.pdo-build) and [here](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/docker/sawtooth-pdo.sgx.yaml), if you run manually in a docker container there are a number of things you have to take care of -- given the complexity, there is no documentation for that, and you'll have to look at the notes inside the docker/yaml.compose files.
These are usually handled automatically by docker compose.
To give you some hints:
* you have to set up the ledger yourself, possibly on the host
* you have to pass to the container: the host network, the SGX key material, the SGX aesmd service, the ledger key, the SGX driver. Your command will look like this `docker run --network host -v $PDO_SGX_KEY_ROOT:/project/pdo/src/private-data-objects/build/keys/sgx_mode_hw -v /var/run/aesmd:/var/run/aesmd -v <pdo folder path>/docker/validator-keys:/project/pdo/build/opt/pdo/etc/keys/ledger --device /dev/isgx:/dev/isgx -it --entrypoint bash pdo-sgx-build`
* as the container runs by default in SGX simulation mode, you'll have to configure the environment variables. Something like:
```
export SGX_MODE=HW
unset PDO_SPID PDO_SPID_API_KEY PDO_HOSTNAME
export PDO_LEDGER_URL=http://127.0.0.1:8008
source /project/pdo/src/private-data-objects/build/common-config.sh
```
* finally you can run the configuration builder, ledger registration and tests `make -C /project/pdo/src/private-data-objects/build conf register test`
