### ISSUE TITLE
enclave quote status error: CONFIGURATION_NEEDED

### ISSUE THREAD

**Issue by zlonqi** [hyperledger-labs/private-data-objects#330]
Hi，I am an undergraduate student who just started to study blockchain privacy. I learned about your project from my friend some time ago.  I'm so grateful for this open source project, a fantastic project.
I reinstalled a ubuntu18.04, a clean environment. I builded PDO followed by host_install.md. Everything is ok! 
And  I `make` it after changed the value of SGX_MODE from SIM to HW. It break down at register-with-ledger.sh, its output as follow:

> registering enclave and IAS public key on the ledger
. /root/private-data-objects/bin/activate && /root/private-data-objects/eservice/bin/register-with-ledger.sh
 register-with-ledger.sh: Download IAS certificates and Compute the enclave information
 register-with-ledger.sh: operation failed: eservice-enclave-info --spid ABAC66755CB4E6424B04F96CC07C21C7 --save /tmp/pdo-test.sPkasxVmc --loglevel warn --identity eservice1 --config eservice1.toml enclave.toml --config-dir /root/private-data-objects/opt/pdo/etc/
 register-with-ledger.sh: Clean up temporary files
Makefile:227: recipe for target 'register' failed
make: *** [register] Error 111

`
` 
I tried the following:
When I execute this command alone `eservice-enclave-info --spid ABAC66755CB4E6424B04F96CC07C21C7 ...,` there are no errors.
But I execute this shell file alone `register-with-ledger.sh`, it fail as above.How can I solve it?
I have done as follows：
It can be successfully built and tested in Docker. But I need non-docker build. So I followed by host_install.md now. And I have deployed the sawtooth ledger service on a new ubuntu16.04. The variables are configured correctly，such as PDO_LEDGER_URL.
My plan is as follows：
If PDO in HW mode can be builded successfully, I'll replace Gipsy with Wawaka.

**Comment by zlonqi** [comment]
when I execute wawaka benchmarks in `/root/private-data-objects/contracts/wawaka` with command 
`pdo-test-contract --no-ledger --interpreter wawaka --contract benchmarks/fibonacci  --expressions ./benchmarks/fibonacci/test-short.json --logfile __screen__ --loglevel info`. 
Program output error:
`[WARNING STDERR] unable to load contract source; [Errno 2] file does ot exist: '/root/private-data-objects/contracts/wawaka/_benchmarks/fibonacci'
`
I found the path `benchmarks`  was modified to `_benchmarks`, 
Is this a bug? thank you very much!

**Comment by zlonqi** [comment]
> First of all, I'm very grateful for this open source project, a fantastic project.
> I reinstalled a ubuntu18.04, a clean environment. I builded PDO followed by host_install.md. Everything is ok! And I rebuild it after changed the value of SGX_MODE from SIM to HW. It break down at register-with-ledger.sh, its output as follow:
> `registering enclave and IAS public key on the ledger . /root/private-data-objects/bin/activate && /root/private-data-objects/eservice/bin/register-with-ledger.sh register-with-ledger.sh: Download IAS certificates and Compute the enclave information register-with-ledger.sh: operation failed: eservice-enclave-info --spid ABAC66755CB4E6424B04F96CC07C21C7 --save /tmp/pdo-test.sPkasxVmc --loglevel warn --identity eservice1 --config eservice1.toml enclave.toml --config-dir /root/private-data-objects/opt/pdo/etc/ register-with-ledger.sh: Clean up temporary files Makefile:227: recipe for target 'register' failed make: *** [register] Error 111 `
> I tried the following:
> When I execute this command alone `eservice-enclave-info --spid ABAC66755CB4E6424B04F96CC07C21C7 ...,` there are no errors.
> But I execute this shell file alone `register-with-ledger.sh`, it fail as above.How can I solve it?
> I have done as follows：
> It can be successfully built and tested in Docker. But I need non-docker build. So I followed by host_install.md now. And I have deployed the sawtooth ledger service on a new ubuntu16.04. The variables are configured correctly，such as PDO_LEDGER_URL.
> My plan is as follows：
> If PDO in HW mode can be builded successfully, I'll replace Gipsy with Wawaka.

I got more accurate information: 
` [14:37:20, 40, pdo.eservice.pdo_enclave] invalid report fields
 54 [14:37:20, 30, STDERR] Traceback (most recent call last):
 55 [14:37:20, 30, STDERR]   File "/root/private-data-objects/bin/eservice-enclave-info", line 33, in <module>
 56 [14:37:20, 30, STDERR] sys.exit(load_entry_point('pdo-eservice==0.0.1.dev1', 'console_scripts', 'eservice-enclave-info')())
 57 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
 58 [14:37:20, 30, STDERR] return get_distribution(dist).load_entry_point(group, name)
 59 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
 60 [14:37:20, 30, STDERR] return ep.load()
 61 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
 62 [14:37:20, 30, STDERR] return self.resolve()
 63 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
 64 [14:37:20, 30, STDERR] module = __import__(self.module_name, fromlist=['__name__'], level=0)
 65 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pdo_eservice-0.0.1.dev1-py3.6-linux-x86_64.egg/pdo/eservice/scripts/ESe    rviceEnclaveInfoCLI.py", line 195, in <module>
 66 [14:37:20, 30, STDERR] Main()
 67 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pdo_eservice-0.0.1.dev1-py3.6-linux-x86_64.egg/pdo/eservice/scripts/ESe    rviceEnclaveInfoCLI.py", line 190, in Main
 68 [14:37:20, 30, STDERR] LocalMain(config, spid, save_path)
 69 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pdo_eservice-0.0.1.dev1-py3.6-linux-x86_64.egg/pdo/eservice/scripts/ESe    rviceEnclaveInfoCLI.py", line 102, in LocalMain
70  [14:37:20, 30, STDERR] GetIasCertificates(config)
 71 [14:37:20, 30, STDERR]   File "/root/private-data-objects/lib/python3.6/site-packages/pdo_eservice-0.0.1.dev1-py3.6-linux-x86_64.egg/pdo/eservice/scripts/ESe    rviceEnclaveInfoCLI.py", line 87, in GetIasCertificates
 72 [14:37:20, 30, STDERR] pd_dict =  json.loads(enclave_data.proof_data)
 73 [14:37:20, 30, STDERR] AttributeError
 74 [14:37:20, 30, STDERR] :
 75 [14:37:20, 30, STDERR] 'NoneType' object has no attribute 'proof_data'
`

**Comment by masomel** [comment]
@zlonqi It seems like you're reporting a couple of different issues in this thread, and your first and third messages are related, while the benchmarks issue is separate. If this is correct, could you please open separate issues for the different problems you're having? This'll help us better understand the errors you're reporting, and address each separate issue more effectively. Thank you!

**Comment by bvavala** [comment]
PDO is behaving correctly.
For some reason (I cannot say what exactly), the Intel Attestation Service reports a `CONFIGURATION_NEEDED` status for your hardware attestation.
Such status is currently not accepted in PDO.
You can see it [here](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/eservice/pdo/eservice/pdo_enclave.py#L313) (lines 313-317).

However, you (developer/user) may want to change that.
As described in the [SGX attestation API spec](https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf), your quote was correctly verified; the platform was not identified as compromised, but some configuration is necessary.
So, it is up to you to decide whether you want to accept such a quote or not.

You can modify PDO's behavior by updating the code snippet linked above as follows -- I have not tested the code! -- to display a warning, without failing:
```
if _ias.last_verification_error() == "GROUP_OUT_OF_DATE":
                logger.warning("failure GROUP_OUT_OF_DATE (update your BIOS/microcode!!!) keep going")
elif _ias.last_verification_error() == "CONFIGURATION_NEEDED":
                logger.warning("Warning: CONFIGURATION_NEEDED, keep going")
else:
                logger.error("invalid report fields")
                return None
```

This part clearly needs some refactoring from our side.
The user/developer should be able to easily specify what quotes are acceptable, without modifying the code.
So, thanks for spotting that!

**Comment by masomel** [comment]
@zlonqi Thanks for the update. Did you resolve the issues with running the benchmarks? If not, please feel free to open an new issue for this, so I can help you resolve this.

**Comment by zlonqi** [comment]
> PDO is behaving correctly.
> For some reason (I cannot say what exactly), the Intel Attestation Service reports a `CONFIGURATION_NEEDED` status for your hardware attestation.
> Such status is currently not accepted in PDO.
> You can see it [here](https://github.com/hyperledger-labs/private-data-objects/blob/0f5f3b16058e7ce51fc043f8ab337c86f6048a5b/eservice/pdo/eservice/pdo_enclave.py#L313) (lines 313-317).
> 
> However, you (developer/user) may want to change that.
> As described in the [SGX attestation API spec](https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf), your quote was correctly verified; the platform was not identified as compromised, but some configuration is necessary.
> So, it is up to you to decide whether you want to accept such a quote or not.
> 
> You can modify PDO's behavior by updating the code snippet linked above as follows -- I have not tested the code! -- to display a warning, without failing:
> 
> ```
> if _ias.last_verification_error() == "GROUP_OUT_OF_DATE":
>                 logger.warning("failure GROUP_OUT_OF_DATE (update your BIOS/microcode!!!) keep going")
> elif _ias.last_verification_error() == "CONFIGURATION_NEEDED":
>                 logger.warning("Warning: CONFIGURATION_NEEDED, keep going")
> else:
>                 logger.error("invalid report fields")
>                 return None
> ```
> 
> This part clearly needs some refactoring from our side.
> The user/developer should be able to easily specify what quotes are acceptable, without modifying the code.
> So, thanks for spotting that!

bvavala, thank you very much. I think it will be work.

**Comment by zlonqi** [comment]
> @zlonqi Thanks for the update. Did you resolve the issues with running the benchmarks? If not, please feel free to open an new issue for this, so I can help you resolve this.

a good advice.
