### ISSUE TITLE
Can Hyperledger PDO be run on WSL2 of Ubuntu 20.04?

### ISSUE THREAD

**Issue by mavisguan** [hyperledger-labs/private-data-objects#387]
Hi,
I was trying to build Hyperledger PDO locally on my WSL2, but kept on failing with strange errors when I run make test. I was wondering about these two questions:
1. Have you tested the installation process successfully on WSL2? (I wonder if subtle difference between common linux system and WSL causes the failure)
2. When I run the command `make test` under `/docker` subdirectory, it always fail at this command
`RUN wget -q -P /tmp https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk_12.0`
![image](https://user-images.githubusercontent.com/58137527/206828744-69633f67-9df8-4129-8adf-fe636adc42eb.png)
There seem to be a timeout, I wonder if you know how to solve the problem?
Thank you so much!

**Comment by bvavala** [comment]
Hi,
1. no, as far as I know, but I don't currently see any reason why this would not work. I hope you can investigate and report on that, as the information can potentially be useful for other users!
2. I would double check the network connection. The previous commands are all cached, and only the command that fails seems to be actually trying to access the network.

**Comment by mavisguan** [comment]
Many thanks for your reply! I'll check on this later if I get time.

**Comment by cmickeyb** [comment]
There is a new client-only build ("make client" in the build directory). The client can be run on ubuntu 22.04 on wsl (that's my client/contract development platform). I have been able to run docker images on ubuntu 22.04 with wsl2 on windows 11.
