### ISSUE TITLE
Incorporate the python script building infrastructure from the exchange contracts

### ISSUE THREAD

**Issue by cmickeyb** [hyperledger-labs/private-data-objects#410]
Other projects have advanced scripting for PDO. Suggest we incorporate some of those advances that allow sharing of code between pdo shell plugins and python only scripts.

**Comment by prakashngit** [comment]
@cmickeyb  Is this issue still relevant for the PDO repo ?

**Comment by cmickeyb** [comment]
Addressed in #452
