### ISSUE TITLE
Consolidation of register-with-ledger step

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/private-data-objects#415]
The register-with-ledger step is an operation that must be performed after the eservice is built and the ledger is up to make sure that the transaction processor can validate the enclave attestation (i.e., the proof data) properly.

Right now there are multiple issues with this step.
* we don't call the registration for sawtooth in sim mode -- rather, we start sawtooth in debug mode (to accept empty proof data)
* in ccf, following the merge of #406 , we call it in two different places, for sim and hw mode respectively
    * the former works behind a proxy, because the registration is called from the ccf container with empty data
    * the latter does not work behind a proxy because the registration is called (similarly to the sawtooth one) from a different container. In this case, there are proxy and/or certificate issues, which are fully explained in #413 .

In an ideal scenario,
* the registration step is called from a single place -- a good candidate is where it is right now for sawtooth, and for ccf in hw mode only.
* the ccf container does not need to be aware of the SGX_MODE variable
#413 partially addresses these issues, by solving the proxy issue -- so the registration step can be consolidated.
Other PRs in the pipeline will take care of refactoring the docker/docker-compose files, containers and variables.

**Comment by cmickeyb** [comment]
The proposed evolution of the docker containers should support a canonical registration "at the right point" in the process. 

We should also move from putting "register" as a Makefile target & should just use single script that can load modules for registering CCF and/or some other ledger.

**Comment by prakashngit** [comment]
Tracked via 467, 463. @cmickeyb  @bvavala  If you are OK, I will close this Issue

**Comment by prakashngit** [comment]
Closed, after merge of https://github.com/hyperledger-labs/private-data-objects/pull/467,.
