### ISSUE TITLE
Fix Script to determine whether CCF TP is ready for user TXNs

### ISSUE THREAD

**Issue by prakashngit** [hyperledger-labs/private-data-objects#424]
Currently we have check-for-ccf-keys.sh as a proxy to determine whether CCF TP is ready for user txns. Based on observations from both @bvavala  and @cmickeyb, it seems insufficient given some of the recent PRs. 

We need to re-visit check-for-ccf-keys.sh, rename it as is-ccf-tp-ready.sh and define it properly.

**Comment by cmickeyb** [comment]
Rather than checking for the keys (which has any number of ways to break), is there a request we can ask of the TP? Similar to what we use the /info path for in each of the other services.

**Comment by cmickeyb** [comment]
Is there a reason why we cant use the ping transaction? The ccf tp has a script ping_test.py that can at least be used to test for liveness.

**Comment by prakashngit** [comment]
@cmickeyb Is this Issue still relevant after 468?

**Comment by prakashngit** [comment]
I think this issue can be closed now, after the recent improvements to CCF TP start up ? @cmickeyb  Please comment.
