### ISSUE TITLE
Implement digital wallet app

### ISSUE THREAD

**Issue by marcelamelara** [hyperledger-labs/private-data-objects#429]
A PDO is a smart contract that runs inside of an Intel SGX enclave. This gives us a way to implement a digital wallet application with additional confidentiality and integrity guarantees.

Using the PDO [contract library](../tree/main/contracts/wawaka/common/), this digital wallet app should manage a set of cyrptographic key pairs for a user.

Tasks: TBD

**Comment by prakashngit** [comment]
may be this should be an issue on the PDO contracts repo ?

**Comment by marcelamelara** [comment]
yes, this is for a contract.

**Comment by cmickeyb** [comment]
Closing this and re-opening in the PDO contracts repository.
Issue [30](https://github.com/hyperledger-labs/pdo-contracts/issues/30)
