### ISSUE TITLE
Should ReservedMemExecutable be set to 0 or 1?

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/private-data-objects#495]
The WAMR interpreter requires ReservedMem inside the enclave for its operations -- see [WAMR](https://github.com/bytecodealliance/wasm-micro-runtime/blob/f096b2fa387f07fcb25fbb12e7ab219661aeb186/doc/linux_sgx.md?plain=1#L123) and the `ReservedMemExecutable` field in the eservice enclave xml file.
If AoT or jitted code is used, then the memory has to be executable. Otherwise, that is not necessary.
With that said, is it ok to leave the `ReservedMemExecutable` field set to 1, or should it be set to 0?

**Comment by cmickeyb** [comment]
Until we upgrade WAMR, i suggest that we not change the setting. the newer versions of WAMR have a different bug that we have to address first.

**Comment by cmickeyb** [comment]
We decided to keep this 1 for now.
