### ISSUE TITLE
Private Data Objects (PDO) Not be confused with Private Data Collection in Fabric 

### ISSUE THREAD

**Issue by nathanawmk** [hyperledger-labs/private-data-objects#75]
Was having a discussion on private data object (PDO) with one of my colleagues when he thought I was referring to private data collection in Fabric v1.2. It is only a small difference (object vs collection)

https://hyperledger-fabric.readthedocs.io/en/release-1.2/private-data/private-data.html

Any idea if we can differentiate private data objects (PDO) further? 

Nathan Aw (Singapore)

**Comment by bvavala** [comment]
My understanding is that a PDC is defined as the (private) data and its hash. Then a set of PDC members can access and share such data. 
A PDO instead binds data to a specific contract code, and privacy is preserved by means of hardware-based security mechanisms. Contract participants are authenticated by a contract and can only invoke methods (i.e., they cannot access the private data directly). As a consequence, by construction, the participants are required to use the interface defined by a contract to access/modify/insert/read/etc. the contract data.
For additional details, please take a look at the PDO Overview (https://arxiv.org/pdf/1807.05686.pdf).
