### ISSUE TITLE
add python builds to Dockerfile

### ISSUE THREAD

**Issue by brenzi** [hyperledger-labs/private-data-objects#99]
I've successfully followed your doc and could run the eservice python tests 
```
test-contract.py
test-request.py
test-secrets.py
```
In order to have a development environment, I thought I'd extend your Dockerfile to include building the python stuff up to running the tests above

Here's my try: https://github.com/encointer/encointer-sdk/raw/master/docker/Dockerfile.pdo-dev

Unfortunately I run into a supposed docker bug as the image grows indefinately during build (after building the "pdo/common" layer) until it fills up my partition. That bug is out of scope here, but do you have any plans in completing your Dockerfile.pdo-dev and yaml so developers could start to implement contracts directly?

**Comment by g2flyer** [comment]
@brenzi i don't think you failed due to a docker bug but the build of common generates very large test files.  See pull request #101 for a second dockerfile which also builds pdo code itself and deals (arguably a bit crudely with that test file).  Note, though, that this will with current build process work only for simulator mode.   

For the bigger question regarding docker files and having end to end docker-compose files.  While that certainly could be interesting, the way pdo and sawtooth build and also don't necessarily match in base OS requirements, it's not immediately clear how best to do that.  Also so far no concrete requirements of such and intended uses were clearly articulated.  Any thoughts on this are very welcome!

**Comment by brenzi** [comment]
Thanks, that pull request might work for me, I'll check that.

I'll articulate my requirement, but I'm open to alternative approaches:
* `docker-compose <some yaml file> up`
  * this should start containers with validator, pdo transaction processor (pdo-tp), pdo dev shell (pdo-dev), set up transaction families for pdo, register pdo tp
  * my first attempt is here (very close to sawtooth example): https://github.com/encointer/encointer-sdk/blob/master/docker/sawtooth-pdo.yaml
* I'd like to `docker exec -it pdo-dev bash` and run above PDO tests successfully
* Then I'd like to use pdo-dev to develop my own Gipsy PDO contracts

The above should solve the problem of different ubuntu dist requirements  for sawtooth (16.04) and PDO (18.04)

Is there a simple way to mock sawtooth and just develop PDO contracts?

**Comment by brenzi** [comment]
Just wanted to add that the above indeed worked. If this is of help for anyone, I completed a docker setup to run PDO tp (running on xenial) and PDO eservice tests or develop your own PDO contracts (running on bionic):
https://github.com/encointer/encointer-sdk

**Comment by cmickeyb** [comment]
@brenzi can you provide a review for the docker PR that @g2flyer pushed? i don't have a setup for testing.

**Comment by brenzi** [comment]
@g2flyer's commit worked for me. I just extended his script to include all python stuff

**Comment by cmickeyb** [comment]
@brenzi thanks for your feedback. I'll merge the docker PR. If you want to be more formally part of the project (submit/review PRs), just let me know.

**Comment by brenzi** [comment]
@cmickeyb  thanks for your offer. As I'm currently working with PDO for [my project](https://encointer.org) , I guess there might be pull requests from my side soon. So yes, I'd appreciate it if you could add me to the project. I'd be happy to contribute.

**Comment by g2flyer** [comment]
> Just wanted to add that the above indeed worked. If this is of help for anyone, I completed a docker setup to run PDO tp (running on xenial) and PDO eservice tests or develop your own PDO contracts (running on bionic):
> https://github.com/encointer/encointer-sdk

@brenzi Thanks for taking a stab at docker-compose. I've extended that now into PR#13 into somewhat more versatile configuration and also in docker support for building in SGX HW mode. I've tried to add you there as reviewer but similar to Mic it didn't let me add you. If you have some thoughs and feedback, though, on the PR, please let me know (as comments on that PR). Thanks!

**Comment by cmickeyb** [comment]
closing... docker improvements now support all sawtooth and pdo components.
